export enum MateriasProfesor{
    MATEMATICAS = 'matemáticas',
    ESPANOL = 'español',
    BIOLOGIA = 'biología',
    FISICA = 'física',
    QUIMICA = 'química',
    INGLES = 'inglés',
    HISTORIA = 'historia',
    GEOGRAFIA = 'geografía',
    EDUCACION_FISICA = 'educación física',
    INFORMATICA = 'informática',
    FILOSOFIA = 'filosofía',
    ARTES_PLASTICAS = 'artes plasticas',
    MUSICA = 'música',
} 